CREATE DATABASE ly CHARSET=UTF8;
USE ly;
CREATE TABLE new(
  rid      INT PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(100) NOT NULL DEFAULT '',
  email    VARCHAR(50) NOT NULL DEFAULT '',
  age      INT NOT NULL DEFAULT 0,
  rdate    DATETIME NOT NULL DEFAULT 0,
  uid      INT NOT NULL DEFAULT 0
);
CREATE TABLE touch(
    uid   INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(20),
    upwd  VARCHAR(32)
  );
